# Generated by Django 5.2.14 on 2026-05-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('company', models.CharField(max_length=255, verbose_name='company')),
                ('description', models.TextField(verbose_name='description')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='location')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='posted at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'job post',
                'verbose_name_plural': 'job posts',
                'ordering': ['-posted_at'],
            },
        ),
    ]
