set dotenv-load

# Start development server
serve:
    uv run manage.py runserver

# Run Django migrations
migrate:
    uv run manage.py migrate

# Create a superuser
superuser:
    uv run manage.py createsuperuser

# Start Celery worker
worker:
    uv run celery -A config worker -l info

# Start Celery Beat scheduler
beat:
    uv run celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler

# Compile translation messages
messages:
    uv run manage.py compilemessages

# Make translation messages
makemessages:
    uv run manage.py makemessages -l en

# Start Docker services
up:
    docker compose up -d --wait

# Stop Docker services
down:
    docker compose down

# Run tests
test:
    uv run manage.py test
