install:
    uv sync

dev:
    uv run manage.py runserver

migrate:
    uv run manage.py migrate

makemigrations:
    uv run manage.py makemigrations

shell:
    uv run manage.py shell

superuser:
    uv run manage.py createsuperuser

test:
    uv run manage.py test

worker:
    uv run celery -A config worker -l info

beat:
    uv run celery -A config beat -l info

collectstatic:
    uv run manage.py collectstatic --noinput
