services:
  web:
    build:
      target: dev
    volumes:
      - .:/app
      - /app/.venv
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local
    ports:
      - "8000:8000"

  worker:
    build:
      target: dev
    volumes:
      - .:/app
      - /app/.venv
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local

  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  minio:
    ports:
      - "9000:9000"
