services:
  web:
    build:
      target: dev
    volumes:
      - .:/app
      - /app/.venv
    command: python manage.py runserver 0.0.0.0:8000

  worker:
    build:
      target: dev
    volumes:
      - .:/app
      - /app/.venv

  db:
    ports:
      - "127.0.0.1:5433:5432"

  redis:
    ports:
      - "127.0.0.1:6379:6379"
